blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("articles/", views.ArticleListView.as_view(), name="article_list"),
    path("article/<int:pk>", views.ArticleDetailView.as_view(), name="article_detail"),
    path(
        "article/<int:pk>/edit",
        views.ArticleUpdateView.as_view(),
        name="article_update",
    ),
    path("article/add", views.ArticleCreateView.as_view(), name="article_create"),
]

hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="homepage"),
    path("admin/", admin.site.urls),
    path("wiki/", include("wiki.urls")),
    path("forum/", include("forum.urls")),
    path("blog/", include("blog.urls")),
    path("merchstore/", include("merchstore.urls")),
    path("commissions/", include("commissions.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user/", include("user_management.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wiki/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleCreateView,
    ArticleDetailView,
    ArticleUpdateView,
    ImageCreateView,
    ImageUpdateView,
    ImageDeleteView,
)

app_name = "wiki"
urlpatterns = [
    path("articles/", ArticleListView.as_view(), name="article_list"),
    path("article/add/", ArticleCreateView.as_view(), name="article_create"),
    path("article/<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path(
        "article/<int:pk>/edit/",
        ArticleUpdateView.as_view(),
        name="article_update",
    ),
    path("article/<int:pk>/image/add/", ImageCreateView.as_view(), name="image_create"),
    path("image/<int:pk>/edit/", ImageUpdateView.as_view(), name="image_update"),
    path("image/<int:pk>/delete/", ImageDeleteView.as_view(), name="image_delete"),
]

wiki/models.py
from django.db import models
from django.urls import reverse
from user_management.models import Profile


class ArticleCategory(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(
        Profile, null=True, on_delete=models.SET_NULL, related_name="wiki_articles"
    )
    category = models.ForeignKey(
        ArticleCategory,
        on_delete=models.SET_NULL,
        null=True,
        related_name="articles",
    )
    header_image = models.ImageField(
        upload_to="wiki/images/", default="images/placeholder.png"
    )
    entry = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"{self.title} by {self.author}"

    def get_absolute_url(self):
        return reverse("wiki:article_detail", kwargs={"pk": self.id})


class Comment(models.Model):
    author = models.ForeignKey(
        Profile, null=True, on_delete=models.SET_NULL, related_name="wiki_comments"
    )
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name="comments"
    )
    entry = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment by {self.author} on {self.article.title}"


class Image(models.Model):
    article = models.ForeignKey(
        Article, related_name="images", on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to="wiki/images/")
    description = models.TextField()

    def __str__(self):
        return f"Image for {self.article.title}"
        return self.title

wiki/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    UpdateView,
    DeleteView,
)
from .models import Article, Comment, Image, ArticleCategory
from .forms import CommentForm
from django.contrib.auth.mixins import LoginRequiredMixin


class ArticleListView(ListView):
    model = Article
    template_name = "wiki/article_list.html"
    context_object_name = "articles"

    def get_queryset(self):
        return Article.objects.select_related("category", "author").order_by(
            "category__name", "title"
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = ArticleCategory.objects.all()
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = ["title", "category", "entry", "header_image"]
    template_name_suffix = "_create"

    def form_valid(self, form):
        article = form.save(commit=False)
        article.author = self.request.user.profile
        article.save()
        return super().form_valid(form)


class ArticleUpdateView(LoginRequiredMixin, UpdateView):
    model = Article
    fields = ["title", "category", "entry", "header_image"]
    template_name_suffix = "_update"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.get_object()
        context["images"] = Image.objects.filter(article=article)
        return context

    def get(self, request, *args, **kwargs):
        affected_article = get_object_or_404(Article, pk=self.kwargs["pk"])
        if request.user.profile != affected_article.author:
            return redirect(reverse_lazy("wiki:article_list"))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        affected_article = get_object_or_404(Article, pk=self.kwargs["pk"])
        if (
            request.user.is_authenticated
            and request.user.profile != affected_article.author
        ):
            return redirect(reverse_lazy("wiki:article_list"))
        return super().post(request, *args, **kwargs)


class ArticleDetailView(DetailView):
    model = Article
    template_name = "wiki/article_detail.html"
    context_object_name = "article"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.get_object()

        context["related_articles"] = article.category.articles.exclude(pk=article.pk)[
            :2
        ]
        context["comments"] = Comment.objects.filter(article=article).order_by(
            "-created_on"
        )

        if self.request.user.is_authenticated:
            context["comment_form"] = CommentForm()

        context["images"] = Image.objects.filter(article=article)

        if article.author == self.request.user:
            context["edit_link"] = True

        return context

    def post(self, request, *args, **kwargs):
        article = self.get_object()

        if request.user.is_authenticated:
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.article = article
                comment.author = request.user.profile
                comment.save()
                return redirect("wiki:article_detail", pk=article.pk)
        return HttpResponse("You must be logged in to comment", status=403)


class ImageCreateView(LoginRequiredMixin, CreateView):
    model = Image
    fields = ["image", "description"]
    template_name_suffix = "_create"

    def get(self, request, *args, **kwargs):
        affected_article = get_object_or_404(Article, pk=self.kwargs["pk"])
        if request.user.profile != affected_article.author:
            return redirect(reverse_lazy("wiki:article_list"))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        print(self.kwargs)
        image = form.save(commit=False)
        image.article = Article.objects.get(pk=self.kwargs["pk"])
        image.save()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        affected_article = get_object_or_404(Article, pk=self.kwargs["pk"])
        if (
            request.user.is_authenticated
            and request.user.profile != affected_article.author
        ):
            return redirect(reverse_lazy("wiki:article_list"))
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        return Article.objects.get(pk=self.kwargs["pk"]).get_absolute_url()


class ImageUpdateView(LoginRequiredMixin, UpdateView):
    model = Image
    fields = ["description"]
    template_name_suffix = "_update"

    def get(self, request, *args, **kwargs):
        image = self.get_object()
        if request.user.profile != image.article.author:
            return redirect(reverse_lazy("wiki:article_list"))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        image = self.get_object()
        if (
            request.user.is_authenticated
            and request.user.profile != image.article.author
        ):
            return redirect(reverse_lazy("wiki:article_list"))
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        image = self.get_object()
        return Article.objects.get(pk=image.article.pk).get_absolute_url()


class ImageDeleteView(LoginRequiredMixin, DeleteView):
    model = Image

    def get(self, request, *args, **kwargs):
        image = self.get_object()
        if request.user.profile != image.article.author:
            return redirect(reverse_lazy("wiki:article_list"))
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        image = self.get_object()
        if (
            request.user.is_authenticated
            and request.user.profile != image.article.author
        ):
            return redirect(reverse_lazy("wiki:article_list"))
        return super().post(request, *args, **kwargs)

    def get_success_url(self):
        image = self.get_object()
        return Article.objects.get(pk=image.article.pk).get_absolute_url()

wiki/templates/wiki/article_create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Create Article{% endblock %}

{% block content %}
<main class="card">
    <h1>Write an Article</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Publish</button>
    </form>

    <p>
        <a href="{% url 'wiki:article_list' %}">Back to All Articles</a>
    </p>
</main>
{% endblock %}

wiki/templates/wiki/article_detail.html
{% extends 'base.html' %}
{% load static %}
    {% block headcontent %}
    <link rel="stylesheet" href="{% static 'forum/detail.css' %}">
    <link rel="stylesheet" href="{% static 'wiki/style.css' %}">
    {% endblock %}
    {% block content %}
    <main class="white-bg-detail">
        <section class="thread-content">
            <section class="thread-header">
                <section class="thread-meta">
                    <h1>{{ article.title }}</h1>
                    <p>Category: {{ article.category }}</p>
                    <p>Created On: {{ article.created_on|date:"m/d/Y" }}</p>
                    <p>Updated On: {{ article.updated_on|date:"m/d/Y" }}</p>
                    <p>Entry Author: {{ article.author }}</p>
                </section>
                {% if user.profile == article.author %}
                <a href="{% url 'wiki:article_update' article.id %}" class="button">Edit Post</a>
                {% endif %}
            </section>
            <section class="article-entry">
                <img src="{{ article.header_image.url }}" alt="">
                <p class="thread-entry">{{ article.entry|linebreaksbr }}</p>
            </section>
            <section class="related-threads">
                <h2>Related Threads</h2>
                <section class="related-links">
                    {% for article in related_articles %}
                    <a href="{% url 'wiki:article_detail' article.id %}">{{ article.title }}</a>
                    {% if not forloop.last %}, {% endif %}
                    {% empty %}
                    <p>No related articles found.</p>
                    {% endfor %}
                </section>
            </section>
        </section>
        {% if article.images.exists %}
            <section class="image-gallery">
                <h2>Image Gallery</h2>
                <section class="image-table">
                {% for image in article.images.all %}
                    <article class="gallery-item">
                    <div class="gallery-image"><img src="{{ image.image.url }}" alt="{{ image.description }}"></div>
                        <p>{{ image.description }}</p>
                    </article>
                {% endfor %}
                </section>
            </section>
        {% endif %}

        <section class="comments-section">
            {% if user.is_authenticated %}
                <form method="post" class="comment-form">
                    {% csrf_token %}
                    <input type="text" name="entry" placeholder="Write a comment..."/>
                    <button type="submit">Post</button>
                </form>
            {% endif %}
            <section class="comments-list">
                {% for comment in comments %}
                <section class="comment">
                    <p class="comment-header">
                        {{ comment.author.user.profile.name }} | {{ comment.created_on|date:"m/d/Y" }}
                    </p>
                    <p>{{ comment.entry|linebreaksbr }}</p>
                </section>
                {% empty %}
                <p>No comments yet.</p>
                {% endfor %}
            </section>
        </section>
    </main>
    {% endblock %}

wiki/templates/wiki/article_list.html
{% extends 'base.html' %}
{% load static %}
	{% block headcontent %}
	<link rel="stylesheet" href="{% static 'wiki/style.css' %}">
	{% endblock %}
	{% block content %}
	<main class="two-col">
		{% if user.is_authenticated %}
		<section class="card user-articles">
			<section class="top">
				<h1>Your Articles</h1>
				<ul class="fullw-list">
					{% for article in user.profile.wiki_articles.all %}
					<li>
						<a href="{% url 'wiki:article_detail' article.id %}">{{ article.title }}</a>
					</li>
					{% empty %}
					<li>No articles written by you.</li>
					{% endfor %}
				</ul>
			</section>
			<a href="{% url 'wiki:article_create' %}" class="button">+ Write a New Article</a>
		</section>
		{% endif %}

		<section class="card all-items">
			<h1>All Articles</h1>
			{% for category in categories %}
			<h2>{{ category.name }}</h2>
			<ul class="fullw-list">
				{% for article in category.articles.all %}
				{% if article.author != user.profile %}
				<li>
					<a href="{% url 'wiki:article_detail' article.id %}">{{ article.title }}</a>
				</li>
				{% endif %}
				{% empty %}
				<li>No articles in this category.</li>
				{% endfor %}
			</ul>
			{% endfor %}
		</section>
	</main>
	{% endblock %}

wiki/templates/wiki/article_update.html
{% extends 'wiki/base.html' %}

{% load static %}

    {% block title %}Update Article - {{ article.title }}{% endblock %}

    {% block headcontent %}
    <link rel="stylesheet" href="{% static 'wiki/style.css' %}" />
    {% endblock %}

    {% block content %}
    <main>
        <section class="card">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Save Changes</button>
            </form>
            <a href="{% url 'wiki:article_detail' article.pk %}"><p>Back to Article</p></a>
        </section>
        <section class="card">
            <h1>Your Images</h1>
            <a href="{% url 'wiki:image_create' object.id %}" class="button">Add Image</a>
            <section class="image-table">
                {% for image in images %}
                <article>
                    <div><img src="{{ image.image.url }}" alt="{{ image.description }}"></div>
                    <p>{{ image.description }}</p>
                    <section class="edit-buttons">
                        <a href="{% url 'wiki:image_update' image.pk %}" class="button">Edit</a>
                        <a href="{% url 'wiki:image_delete' image.pk %}" class="button">Delete</a>
                    </section>
                </article>
                {% endfor %}
            </section>
        </section>
    </main>
    {% endblock %}

wiki/templates/wiki/base.html
{% extends 'base.html' %}
{% load static %}
{% block headcontent %}
    <link rel="stylesheet" href="{% static 'wiki/style.css' %}">
{% endblock %}
{% block title %}Wiki{% endblock %}

wiki/templates/wiki/image_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Delete Image{% endblock %}

{% block content %}
<main class="card">
    <form method="post" enctype="multipart/form-data">
        <p>Are you sure you want to delete this image?</p>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Confirm</button>
    </form>
</main>
{% endblock %}

wiki/templates/wiki/image_create.html
{% extends "base.html" %}
{% load static %}

{% block title %}Add Image to Article{% endblock %}

{% block content %}
<main class="card">
    <h1>Add Image to Article</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Publish</button>
    </form>
</main>
{% endblock %}

wiki/templates/wiki/image_update.html
{% extends "base.html" %}
{% load static %}

{% block title %}Update Image Description{% endblock %}

{% block content %}
<main class="card">
    <h1>Update Image description</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Publish</button>
    </form>
</main>
{% endblock %}