blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("articles/", views.ArticleListView.as_view(), name="article_list"),
    path("article/<int:pk>", views.ArticleDetailView.as_view(), name="article_detail"),
    path(
        "article/<int:pk>/edit",
        views.ArticleUpdateView.as_view(),
        name="article_update",
    ),
    path("article/add", views.ArticleCreateView.as_view(), name="article_create"),
]

commissions/urls.py
from django.urls import path
from . import views

app_name = "commissions"

urlpatterns = [
    path("list/", views.CommissionListView.as_view(), name="commission_list"),
    path(
        "detail/<int:pk>/",
        views.CommissionDetailView.as_view(),
        name="commission_detail",
    ),
    path(
        "<int:pk>/edit/", views.CommissionUpdateView.as_view(), name="commission_update"
    ),
    path("add/", views.CommissionCreateView.as_view(), name="commission_add"),
    path("job/<int:pk>/", views.JobView.as_view(), name="job_view"),
    path("detail/<int:pk>/job/add/", views.JobCreateView.as_view(), name="job_create"),
    path("job/<int:pk>/edit/", views.JobUpdateView.as_view(), name="job_update"),
]

hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="homepage"),
    path("admin/", admin.site.urls),
    path("wiki/", include("wiki.urls")),
    path("forum/", include("forum.urls")),
    path("blog/", include("blog.urls")),
    path("merchstore/", include("merchstore.urls")),
    path("commissions/", include("commissions.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user/", include("user_management.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commissions/models.py
from django.db import models
from django.urls import reverse
from django.core.validators import MinValueValidator
from user_management.models import Profile


class Commission(models.Model):
    class CommissionStatusOptions(models.TextChoices):
        OPEN = "Open"
        FULL = "Full"
        COMPLETED = "Completed"
        DISCONTINUED = "Discontinued"

    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.CharField(
        max_length=15,
        default=CommissionStatusOptions.OPEN,
        choices=CommissionStatusOptions,
    )
    # The list view requires us to track commissions created by the User but they don't have a creator field
    creator = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="commissions"
    )
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("commissions:commission_detail", kwargs={"pk": self.pk})

    def fill_job(self):
        """
        This method is called everytime a job is filled. It then checks if all jobs are filled and updates the status of the commission.
        """

        if self.status in [
            self.CommissionStatusOptions.COMPLETED,
            self.CommissionStatusOptions.DISCONTINUED,
        ]:
            return

        if not (self.jobs.filter(status=Job.JobStatusOptions.OPEN).exists()):
            self.status = self.CommissionStatusOptions.FULL
            self.save()


class Job(models.Model):
    class JobStatusOptions(models.TextChoices):
        OPEN = "Open"
        FULL = "Full"

    commission = models.ForeignKey(
        Commission, on_delete=models.CASCADE, related_name="jobs"
    )
    role = models.TextField(max_length=255)
    manpower_required = models.PositiveIntegerField(validators=[MinValueValidator(1)])
    status = models.CharField(
        max_length=15, default=JobStatusOptions.OPEN, choices=JobStatusOptions
    )

    class Meta:
        ordering = ["status", "-manpower_required", "role"]

    def __str__(self):
        return self.role

    def get_absolute_url(self):
        return reverse("commissions:job_view", kwargs={"pk": self.pk})

    def open_manpower(self):
        accepted_applicants = JobApplication.objects.filter(
            job=self.id, status=JobApplication.ApplicationStatusOptions.ACCEPTED
        ).count()
        return self.manpower_required - accepted_applicants

    def accept_applicant(self):
        if self.open_manpower() == 0:
            self.set_full()

    def set_full(self):
        self.status = self.JobStatusOptions.FULL
        self.save()
        self.commission.fill_job()


class JobApplication(models.Model):
    class ApplicationStatusOptions(models.TextChoices):
        PENDING = "Pending"
        ACCEPTED = "Accepted"
        REJECTED = "Rejected"

    status = models.CharField(
        max_length=15,
        default=ApplicationStatusOptions.PENDING,
        choices=ApplicationStatusOptions,
    )
    job = models.ForeignKey(Job, on_delete=models.CASCADE, related_name="applications")
    applicant = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="applications"
    )
    applied_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["status", "-applied_on"]

    def get_absolute_url(self):
        return reverse("commissions:job_view", kwargs={"pk": self.job.pk})

    def __str__(self):
        return f"Application for {self.job}"

    def accept_application(self):
        self.status = self.ApplicationStatusOptions.ACCEPTED
        self.save()
        self.job.accept_applicant()

    def reject_application(self):
        self.status = self.ApplicationStatusOptions.REJECTED
        self.save()

commissions/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Commission, Job, JobApplication


class CommissionListView(ListView):
    model = Commission
    template_name = "commissions/commissions_list.html"
    context_object_name = "commissions"


class CommissionDetailView(DetailView):
    model = Commission
    template_name = "commissions/commissions_detail.html"
    context_object_name = "commission"

    def post(self, request, *args, **kwargs):
        job = get_object_or_404(Job, pk=self.kwargs["pk"])
        JobApplication.objects.create(job=job, applicant=self.request.user.profile)
        return redirect(self.request.path_info)


class CommissionUpdateView(LoginRequiredMixin, UpdateView):
    model = Commission
    fields = ["title", "description", "status"]
    template_name_suffix = "_update"

    def get(self, request, *args, **kwargs):
        affected_commission = get_object_or_404(Commission, pk=self.kwargs["pk"])
        if request.user.profile != affected_commission.creator:
            return redirect(reverse_lazy("commissions:commission_list"))
        return super().get(request, *args, **kwargs)


class CommissionCreateView(LoginRequiredMixin, CreateView):
    model = Commission
    fields = ["title", "description", "status"]
    template_name_suffix = "_create"

    def form_valid(self, form):
        commission = form.save(commit=False)
        commission.creator = self.request.user.profile
        commission.save()
        return super().form_valid(form)


class JobView(DetailView):
    model = Job
    template_name = "commissions/job_detail.html"
    context_object_name = "job"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["applications"] = self.get_object().applications.filter(
            status=JobApplication.ApplicationStatusOptions.PENDING
        )
        return context

    def post(self, request, *args, **kwargs):
        if "accept" in request.POST:
            app_id = request.POST.get("accept")
            application = get_object_or_404(JobApplication, id=app_id)
            application.accept_application()

        elif "reject" in request.POST:
            app_id = request.POST.get("reject")
            application = get_object_or_404(JobApplication, id=app_id)
            application.reject_application()

        return HttpResponseRedirect(self.request.path_info)


class JobCreateView(CreateView):
    model = Job
    template_name_suffix = "_create"
    fields = ["role", "manpower_required"]

    def form_valid(self, form):
        commission_id = self.kwargs["pk"]
        job = form.save(commit=False)
        job.commission = get_object_or_404(Commission, pk=commission_id)
        job.save()
        return super().form_valid(form)


class JobUpdateView(UpdateView):
    model = Job
    template_name_suffix = "_update"
    fields = ["role", "manpower_required"]

    def get(self, request, *args, **kwargs):
        affected_job = get_object_or_404(Job, pk=self.kwargs["pk"])
        if request.user.profile != affected_job.commission.creator:
            return redirect(reverse_lazy("commissions:commission_list"))
        return super().get(request, *args, **kwargs)

commissions/templates/commissions/commission_create.html
{% extends 'base.html' %}
{% block content %}
<main class="card">
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">+ Add Commission</button>
	</form>
</main>
{% endblock %}

commissions/templates/commissions/commission_create_form.html
{% extends 'base.html' %}
{% block content %}
<main class="card">
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">+ Add Commission</button>
	</form>
</main>
{% endblock %}

commissions/templates/commissions/commission_update.html
{% extends 'base.html' %}
{% block content %}
<main class="card">
	<form action="" method="POST">
		{{ form.as_p }}
		<button type="submit">Update Commission</button>
	</form>
</main>
{% endblock %}

commissions/templates/commissions/commission_update_form.html
{% extends 'base.html' %}
{% block content %}
<main>
	<section class="card">
		<form action="" method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit">Update Commission</button>
		</form>
	<section class="card">
        <h3>Jobs Involved</h3>
        <a href="{% url 'commissions:job_create' object.id %}" class="button">Create Job</a>
        {% for job in jobs %}
        <h2>{{ job.role }}</h2>
        <a href="{% url 'commissions:job_update' job.pk %}" class="button">Edit</a>
        <a href="{% url 'commissions:job_delete' job.pk %}" class="button">Delete</a>
        {% endfor %}
	</section>
</main>
{% endblock %}

commissions/templates/commissions/commissions_detail.html
{% extends 'base.html' %}
{% load static %}
    {% block headcontent %}
    <link rel="stylesheet" href="{% static 'commissions/base.css' %}">
    <link rel="stylesheet" href="{% static 'commissions/commissions_detail.css' %}">
    {% endblock %}
    {% block title %}Commission Detail{% endblock %}
    {% block content %}
    <main class="card">
        <section>
            <h1>Jobs for {{ commission.title }}</h1>
            {% if user.is_authenticated and commission.creator == user.profile %}
                <a href="{% url 'commissions:commission_update' commission.id %}">
                    <p class="button">Edit Commission</p>
                </a>
                <a href="{% url 'commissions:job_create' commission.id %}">
                    <p class="button">Add Job</p>
                </a>
            {% endif %}
        </section>
        <section>
            <ul>
                {% for job in commission.jobs.all %}
                <li class="list-item">
                    <section class="job-header">
                        <h2>{{ job.role }}</h2>
                        <p class="status-chip">{{ job.status }}</p>
                    </section>
                    <section class="job-footer">
                        <p class="manpower">{{ job.open_manpower }} out of {{ job.manpower_required }} slots are still open</p>
                        {% if user.is_authenticated and commission.status == "Open" and object.creator != user.profile %}
                        <form action="" method="POST">
                            {% csrf_token %}
                            <button type="submit">Apply to Job</button>
                        </form>
                        {% elif object.creator == user.profile %}
                        <a href="{% url 'commissions:job_view' job.id %}">
                            <p class="button">Manage Applicants</p>
                        </a>
                        {% endif %}
                    </section>
                </li>
                {% endfor %}
            </ul>
        </section>
    </main>
    {% endblock %}

commissions/templates/commissions/commissions_list.html
{% extends 'base.html' %}
{% load static %}
    {% block title %}Commission List{% endblock %}
    {% block headcontent %}
    <link rel="stylesheet" href="{% static 'commissions/commission_list.css' %}">
    <link rel="stylesheet" href="{% static 'commissions/base.css' %}">
    {% endblock %}
    {% block content %}
    <main>
        {% if user.is_authenticated %}
        <section class="card">
            <section>
                <h1>Your Commissions</h1>
                <ul>
                    {% for commission in user.profile.commissions.all %}
                    <li class="list-item">
                        <section>
                            <a href="{% url 'commissions:commission_detail' commission.id %}"><h2>{{ commission.title }}</h2></a>
                            <p>{{ commission.created_on | date }}</p>
                        </section>
                        <p class="status-chip">{{ commission.status }}</p>
                    </li>
                    {% endfor %}
                </ul>
            </section>
            <section class="full">
                <h1>Commissions You Applied To</h1>
                <ul class="item-list">
                    {% for application in user.profile.applications.all %}
                    <li class="list-item">
                        <section>
                            <a href="{% url 'commissions:commission_detail' application.job.commission.id %}"><h2>{{ application.job.commission.title }}</h2></a>
                            <p>{{ application.job.commission.created_on | date }}</p>
                        </section>
                        <p class="status-chip">{{ application.job.commission.status }}</p>
                    </li>
                    {% endfor %}
                </ul>
                <a href="{% url "commissions:commission_add" %}">
                    <p class="button full">+ Post a new Commission</p>
                </a>
            </section>
        </section>
        {% endif %}

        <section class="card all-commissions">
            <h1>All Commissions</h1>
            <ul>
                {% for commission in commissions.all %}
                <li class="list-item">
                    <section>
                        <a href="{% url 'commissions:commission_detail' commission.id %}"><h2>{{ commission.title }}</h2></a>
                        <p>{{ commission.created_on | date }}</p>
                    </section>
                    <p class="status-chip">{{ commission.status }}</p>
                </li>
                {% endfor %}
            </ul>
        </section>
    </main>
    {% endblock %}

commissions/templates/commissions/job_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Delete Job{% endblock %}

{% block content %}
<main class="card">
    <form method="post" enctype="multipart/form-data">
        <p>Are you sure you want to delete this job?</p>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Confirm</button>
    </form>
</main>
{% endblock %}

commissions/templates/commissions/job_create.html
{% extends 'base.html' %}
{% block content %}
<main class="card">
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">+ Add Job</button>
	</form>
</main>
{% endblock %}

commissions/templates/commissions/job_detail.html
{% extends 'base.html' %}
{% load static %}
    {% block headcontent %}
    <link rel="stylesheet" href="{% static 'commissions/base.css' %}">
    <link rel="stylesheet" href="{% static 'commissions/job_detail.css' %}">
    {% endblock %}
    {% block title %}Job Detail{% endblock %}
    {% block content %}
    <main class="card">
        <h1>Applicants for {{ job.role }}</h1>
        {% if request.user.profile == job.commission.creator %}
            <a href="{% url 'commissions:job_update' job.id %}">
                <p class="button">Edit Job</p>
            </a>
        {% endif %}
        <ul>
            {% for application in applications %}
            <li class="list-item">
                <p>{{ application.applicant.name }}</p>
                <form method="POST" action="">
                    {% csrf_token %}
                    <button name="accept" type="submit" value="{{ application.id }}">Accept</button>
                    <button name="reject" type="submit" value="{{ application.id }}">Reject</button>
                </form>
            </li>
            {% endfor %}
        </ul>
    </main>
    {% endblock %}

commissions/templates/commissions/job_update.html
{% extends 'base.html' %}
{% block content %}
<main class="card">
	<form action="" method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit">Save Job</button>
	</form>
</main>
{% endblock %}