blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("articles/", views.ArticleListView.as_view(), name="article_list"),
    path("article/<int:pk>", views.ArticleDetailView.as_view(), name="article_detail"),
    path(
        "article/<int:pk>/edit",
        views.ArticleUpdateView.as_view(),
        name="article_update",
    ),
    path("article/add", views.ArticleCreateView.as_view(), name="article_create"),
]

commissions/urls.py
from django.urls import path
from . import views

app_name = "commissions"

urlpatterns = [
    path("list/", views.CommissionListView.as_view(), name="commission_list"),
    path(
        "detail/<int:pk>/",
        views.CommissionDetailView.as_view(),
        name="commission_detail",
    ),
    path(
        "<int:pk>/edit/", views.CommissionUpdateView.as_view(), name="commission_update"
    ),
    path("add/", views.CommissionCreateView.as_view(), name="commission_add"),
    path("job/<int:pk>/", views.JobView.as_view(), name="job_view"),
    path("detail/<int:pk>/job/add/", views.JobCreateView.as_view(), name="job_create"),
    path("job/<int:pk>/edit/", views.JobUpdateView.as_view(), name="job_update"),
]

forum/urls.py
from django.urls import path
from .views import ThreadListView, ThreadDetailView, ThreadCreateView, ThreadUpdateView


app_name = "forum"
urlpatterns = [
    path("threads/", ThreadListView.as_view(), name="index"),
    path("thread/<int:pk>/", ThreadDetailView.as_view(), name="thread_detail"),
    path("thread/add/", ThreadCreateView.as_view(), name="thread_create"),
    path("thread/<int:pk>/edit/", ThreadUpdateView.as_view(), name="thread_update"),
]

hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="homepage"),
    path("admin/", admin.site.urls),
    path("wiki/", include("wiki.urls")),
    path("forum/", include("forum.urls")),
    path("blog/", include("blog.urls")),
    path("merchstore/", include("merchstore.urls")),
    path("commissions/", include("commissions.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user/", include("user_management.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchstore/urls.py
from django.urls import path
from . import views

app_name = "merchstore"

urlpatterns = [
    path("items/", views.ProductListView.as_view(), name="product_list"),
    path("item/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("item/add", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "item/<int:pk>/edit", views.ProductUpdateView.as_view(), name="product_update"
    ),
    path("cart", views.CartListView.as_view(), name="cart_list"),
    path("transactions", views.TransactionListView.as_view(), name="transaction_list"),
]

wiki/urls.py
from django.urls import path
from .views import (
    ArticleListView,
    ArticleCreateView,
    ArticleDetailView,
    ArticleUpdateView,
    ImageCreateView,
    ImageUpdateView,
    ImageDeleteView,
)

app_name = "wiki"
urlpatterns = [
    path("articles/", ArticleListView.as_view(), name="article_list"),
    path("article/add/", ArticleCreateView.as_view(), name="article_create"),
    path("article/<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path(
        "article/<int:pk>/edit/",
        ArticleUpdateView.as_view(),
        name="article_update",
    ),
    path("article/<int:pk>/image/add/", ImageCreateView.as_view(), name="image_create"),
    path("image/<int:pk>/edit/", ImageUpdateView.as_view(), name="image_update"),
    path("image/<int:pk>/delete/", ImageDeleteView.as_view(), name="image_delete"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
	{% load static %}
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Hobby Site</title>
		<link rel="stylesheet" href="{% static 'base.css' %}" />
		{% block headcontent %}{% endblock %}
	</head>

	<body>
		<section class="padding with-content">
			<header>
				<nav>
					<section class="nav-links">
						<ul>
							<li><a href="{% url 'homepage' %}">Home</a></li>
							<li><a href="{% url 'merchstore:product_list' %}">Merch</a></li>
							<li><a href="{% url 'commissions:commission_list' %}">Commissions</a></li>
							<li><a href="{% url 'forum:index' %}">Forum</a></li>
							<li><a href="{% url 'wiki:article_list' %}">Wiki</a></li>
							<li><a href="{% url 'blog:article_list' %}">Blog</a></li>
							{% block extra_links %}{% endblock %}
						</ul>
					</section>
					<section class="login-section">
						{% if user.is_authenticated %}
						<p>{{ user.username }}</p>
						<div class="login-link">
							<div class="icon">
								<img src="{% static 'Male User.png' %}" alt="">
							</div>
							<a href="{% url 'password_change' %}">
								<p>Reset Pass</p>
							</a>
							<form action="{% url 'logout' %}" method="post">
								{% csrf_token %}
								<button type="submit">Logout</button>
							</form>
						</div>
						{% else %}
						<a href="{% url 'login' %}">
							<div class="login-link">
								<div class="icon">
									<img src="{% static 'Male User.png' %}" alt="">
								</div>
								<p>Login</p>
							</div>
						</a>
						{% endif %}
					</section>
				</nav>
			</header>
			{% block content %}
			{% endblock %}
		</section>
		<footer>
			<ul>
				<li><a href="{% url 'homepage' %}">Home</a></li>
				<li><a href="{% url 'merchstore:product_list' %}">Merch</a></li>
				<li><a href="{% url 'commissions:commission_list' %}">Commissions</a></li>
				<li><a href="{% url 'forum:index' %}">Forum</a></li>
				<li><a href="{% url 'wiki:article_list' %}">Wiki</a></li>
				<li><a href="{% url 'blog:article_list' %}">Blog</a></li>
			</ul>
		</footer>
	</body>
</html>

templates/homepage.html
{% extends "base.html" %}
{% load static %}
{% block headcontent %}
<link rel="stylesheet" href="{% static 'homepage.css' %}">
{% endblock %}

{% block content %}
<main class="card">
	<section class="content">
		<h1>Group 2's Hobby Site</h1>
		<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's
			standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a
			type specimen book.</p>
	</section>
	<section class="image"><img src="static/robot.svg" alt=""></section>
</main>
{% endblock %}