blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("articles/", views.ArticleListView.as_view(), name="article_list"),
    path("article/<int:pk>", views.ArticleDetailView.as_view(), name="article_detail"),
    path(
        "article/<int:pk>/edit",
        views.ArticleUpdateView.as_view(),
        name="article_update",
    ),
    path("article/add", views.ArticleCreateView.as_view(), name="article_create"),
]

hobbysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="homepage"),
    path("admin/", admin.site.urls),
    path("wiki/", include("wiki.urls")),
    path("forum/", include("forum.urls")),
    path("blog/", include("blog.urls")),
    path("merchstore/", include("merchstore.urls")),
    path("commissions/", include("commissions.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("user/", include("user_management.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchstore/urls.py
from django.urls import path
from . import views

app_name = "merchstore"

urlpatterns = [
    path("items/", views.ProductListView.as_view(), name="product_list"),
    path("item/<int:pk>/", views.ProductDetailView.as_view(), name="product_detail"),
    path("item/add", views.ProductCreateView.as_view(), name="product_create"),
    path(
        "item/<int:pk>/edit", views.ProductUpdateView.as_view(), name="product_update"
    ),
    path("cart", views.CartListView.as_view(), name="cart_list"),
    path("transactions", views.TransactionListView.as_view(), name="transaction_list"),
]

merchstore/models.py
from django.db import models
from django.urls import reverse
from user_management.models import Profile


class ProductType(models.Model):

    name = models.CharField(max_length=255, unique=True)
    description = models.TextField()

    class Meta:
        ordering = ["name"]
        verbose_name = "Product Type"
        verbose_name_plural = "Product Types"

    def __str__(self):
        return self.name


class Product(models.Model):

    def __init__(self, *args, **kwargs):
        super(Product, self).__init__(*args, **kwargs)
        self.update_status(commit=False)

    class ProductStatusChoices(models.TextChoices):
        AVAILABLE = "Available"
        ON_SALE = "On Sale"
        OUT_OF_STOCK = "Out Of Stock"

    name = models.CharField(max_length=255)
    product_type = models.ForeignKey(
        ProductType, null=True, on_delete=models.SET_NULL, related_name="products"
    )
    owner = models.ForeignKey(
        Profile,
        null=False,
        on_delete=models.CASCADE,
        related_name="products",
        default="",
    )
    description = models.TextField(default="A buyable item of this merch store.")
    price = models.DecimalField(max_digits=24, decimal_places=2)
    stock = models.PositiveIntegerField(default=1)
    status = models.CharField(
        max_length=12,
        choices=ProductStatusChoices,
        default=ProductStatusChoices.AVAILABLE,
    )

    class Meta:
        ordering = ["name"]
        verbose_name = "Product"
        verbose_name_plural = "Products"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("merchstore:product_detail", kwargs={"pk": self.id})

    def update_status(self, commit=True):
        if self.status == self.ProductStatusChoices.OUT_OF_STOCK and self.stock > 0:
            self.status = self.ProductStatusChoices.AVAILABLE
        elif self.status == self.ProductStatusChoices.AVAILABLE and self.stock == 0:
            self.status = self.ProductStatusChoices.OUT_OF_STOCK
        if commit:
            self.save()

    def reduce_stock(self, value):
        if value > self.stock:
            raise ValueError(
                f"You only have {self.stock} left in stock. You tried to reduce stock by {value} which is more than what is in stock."
            )
        self.stock = self.stock - value
        self.update_status()
        self.save()


class Transaction(models.Model):

    class TransactionStatusChoices(models.TextChoices):
        ON_CART = "On Cart"
        TO_PAY = "To Pay"
        TO_SHIP = "To Ship"
        TO_RECEIVE = "To Receive"
        DELIVERED = "Delivered"

    buyer = models.ForeignKey(
        Profile, null=True, on_delete=models.SET_NULL, related_name="transaction"
    )
    product = models.ForeignKey(
        Product, null=True, on_delete=models.SET_NULL, related_name="transaction"
    )
    amount = models.PositiveIntegerField()
    status = models.CharField(
        max_length=12,
        choices=TransactionStatusChoices,
        default=TransactionStatusChoices.ON_CART,
    )
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["buyer"]
        verbose_name = "Transaction"
        verbose_name_plural = "Transactions"

    def __str__(self):
        return (
            self.buyer.name
            + "'s "
            + str(self.amount)
            + " instances of "
            + self.product.name
        )
        # Ex: Dino's 5 instances of Chicken Nugget

merchstore/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
from .models import Transaction, Product, ProductType
from user_management.models import Profile


class ProductCreator(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.owner_profile = kwargs.pop("owner", None)
        super().__init__(*args, **kwargs)
        self.fields["owner"].widget = forms.HiddenInput(attrs={"readonly": "true"})
        self.initial["owner"] = self.owner_profile

    class Meta:
        model = Product
        fields = "__all__"
        widgets = {"stock": forms.NumberInput(attrs={"min": "1"})}

merchstore/views.py
from django.shortcuts import get_object_or_404, reverse, redirect
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.views import redirect_to_login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from .models import Product, Transaction
from .forms import ProductCreator


class ProductListView(ListView):
    model = Product
    template_name = "merchstore/product_list.html"
    context_object_name = "products"


class ProductDetailView(DetailView):
    template_name = "merchstore/product_detail.html"
    model = Product
    success_url = reverse_lazy("merchstore:cart_list")
    context_object_name = "product"

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect_to_login(
                reverse_lazy(
                    "merchstore:product_detail",
                    kwargs={"pk": request.POST.get("bought_product")},
                ),
                reverse("login"),
            )
        else:
            affected_product = get_object_or_404(
                Product, pk=request.POST.get("bought_product")
            )
            if len(request.POST.get("amount")) != 0 and affected_product.stock >= int(
                request.POST.get("amount")
            ):
                amount_to_buy = int(request.POST.get("amount"))
                transaction = Transaction()
                transaction.buyer = request.user.profile
                transaction.product = affected_product
                transaction.amount = amount_to_buy
                if (
                    request.user.is_authenticated
                    and request.user.profile != affected_product.owner
                ):
                    transaction.save()
                    affected_product.reduce_stock(transaction.amount)
                else:
                    return redirect(reverse("merchstore:product_list"))
            else:
                return redirect(self.request.path_info)

        return redirect(self.success_url)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductCreator
    template_name_suffix = "_create"

    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super(ProductCreateView, self).get_form_kwargs(*args, **kwargs)
        form_kwargs["owner"] = self.request.user.profile
        return form_kwargs

    def form_valid(self, form):
        if form.cleaned_data["price"] < 0:
            return super().form_invalid(form)
        updated_product = form.save()
        updated_product.update_status()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    template_name_suffix = "_update"
    fields = ["name", "product_type", "description", "price", "stock", "status"]

    def get(self, request, *args, **kwargs):
        affected_product = get_object_or_404(Product, pk=self.kwargs["pk"])
        if request.user.profile != affected_product.owner:
            return redirect(reverse_lazy("merchstore:product_list"))
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        if form.cleaned_data["price"] < 0:
            return super().form_invalid(form)
        updated_product = form.save()
        updated_product.update_status()
        return super().form_valid(form)

    def post(self, request, *args, **kwargs):
        affected_product = get_object_or_404(Product, pk=self.kwargs["pk"])
        if (
            request.user.is_authenticated
            and request.user.profile != affected_product.owner
        ):
            return redirect(reverse_lazy("merchstore:product_list"))
        return super().post(request, *args, **kwargs)


class CartListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = "merchstore/cart_list.html"
    context_object_name = "transactions"

    def get_queryset(self):
        return Transaction.objects.filter(buyer=self.request.user.profile).order_by(
            "product__owner", "-created_on"
        )


class TransactionListView(LoginRequiredMixin, ListView):
    model = Transaction
    template_name = "merchstore/transaction_list.html"
    context_object_name = "transactions"

    def get_queryset(self):
        return Transaction.objects.filter(
            product__owner=self.request.user.profile
        ).order_by("buyer", "-created_on")

merchstore/templates/merchstore/base.html
{% extends 'base.html' %}
{% load static %}
{% block headcontent %}
	<link rel="stylesheet" href="{% static 'merchstore/style.css' %}">
{% endblock %}
{% block title %}Merchstore{% endblock %}
{% block extra_links %}
<li><a href="{% url 'merchstore:cart_list' %}">Cart</a></li>
<li><a href="{% url 'merchstore:transaction_list' %}">Transactions</a></li>
{% endblock %}

merchstore/templates/merchstore/cart_list.html
{% extends 'merchstore/base.html' %}
{% block content %}
<main class="card full-flex">
	<h1>Your Cart</h1>
	{% regroup transactions by product.owner as transactions_by_owner %}
	{% for transaction in transactions_by_owner %}
		<section class="transaction-list">
			<h2>{{ transaction.grouper }}</h2>
			<ul>
				{% for transaction_entry in transaction.list %}
					<li class="product-item">
						<section>
							<p class="bold">{{ transaction_entry.product.product_type }}: {{ transaction_entry.product }}</p>
							<p>PHP {{ transaction_entry.product.price|floatformat:2 }} per item</p>
						</section>
						<section>
							<p>{{ transaction_entry.amount }} bought</p>
							<p class="status-chip">{{ transaction_entry.status }}</p>
						</section>
					</li>
				{% endfor %}
			</ul>
		</section>
	{% endfor %}
</main>
{% endblock %}

merchstore/templates/merchstore/merchstoreItem.html
<!DOCTYPE html>
<html lang = "en-US">

<head>
	<title>Merch Store: {{product.name}}</title>
</head>

<body>
	<div id="headsup">
		<h1>Merch Store: {{product.name}}</h1>
	</div>
	<div id="content">
		<p>Description: {{product.description}}</p>
		<br>
		<p>Product Type: {{product.product_type.name}}</p>
		<br>
		<h4>Price: <b>{{product.price}}</b></h4>
		<br>
	</div>
</body>
</html>

merchstore/templates/merchstore/merchstoreList.html
<!DOCTYPE html>
{% load merchstore_extra_tags %}
<html lang = "en-US">

<head>
	<title>Merch Store: Inventory!</title>
</head>

<body>
	<div id="headsup">
		<h1>Merch Store: Inventory</h1>
	</div>
	<div id="content">
		<h4>Good day! Welcome to the merch store!</h4>
		<br>
		<h5>Here's what we have for today...</h5>
		{% for product_type in inventory %}
			<details>
				<summary>
					<a href="{{product_type.get_absolute_url}}"><b>{{ product_type.name }}</b></a>
				</summary>
				{% for item in product_type|products %}
					<ul>
						<a href="{{item.get_absolute_url}}">{{ item.name }}</a>	
					</ul>
				{% endfor %}
			</details>
			<br>
		{% endfor %}

	</div>

</body>
</html>

merchstore/templates/merchstore/merchstoreSublist.html
<!DOCTYPE html>
<html lang = "en-US">

<head>
	<title>Merch Store: {{product_kind.name}}</title>
</head>

<body>
	<div id="headsup">
		<h1>Merch Store: {{product_kind.name}}</h1>
	</div>
	<div id="content">
		<h4>Description: {{product_kind.description}}</h4>
		<br>
		<h5>Here's what we have for today...</h5>
		{% for item in items %}
			<ul>
				<a href="{{item.get_absolute_url}}">{{ item.name }}</a>	
			</ul>
		{% endfor %}
	</div>
</body>
</html>

merchstore/templates/merchstore/product_create.html
{% extends 'merchstore/base.html' %}
{% block title %}Product Creation{% endblock %}
{% block content %}
<main>
	<section class="card full-flex">
		<form method="post">
			{% csrf_token %}
			<p>{{form.owner.label_tag}}{{user.profile.name}}{{form.owner}}</p>
			{% for field in form %}
				{% if field.label != "Owner" %}
					{% for error in field.errors %}
						<p>{{error}}</p>
					{% endfor %}
					<p>{{field.label_tag}}{{field}}</p>
				{% endif %}
			{% endfor%}
			<button type="submit" name="form_type" value="product">Create</button>
		</form>
	</section>
</main>
{% endblock %}

merchstore/templates/merchstore/product_detail.html
{% extends 'merchstore/base.html' %}
{% block title %}Merch Store: {{product.name}}{% endblock %}
{% block content %}
	<main class="card product-detail">
		<h1 class="product-owner">From: {{ product.owner.name }}</h1>
		<section class="product-content">
			<section class="product-header">
				<h2>{{product.product_type}}: {{ product.name }}</h2>
				<p>PHP {{ product.price|floatformat:2 }}</p>
			</section>
			<h2>Description:</h2>
			<p>{{ product.description }}</p>
			<hr>
			<section class="product-footer">
				<p>{{ product.stock }} in stock</p>
				<p class="status-chip">{{ product.status }}</p>
			</section>
		</section>
		<section>
			{% if product.owner != user.profile %}
				{% if product.stock != 0 %}
				<form method="post">
					{% csrf_token %}
					<input type="number" min=1 name="amount" />
					<button type="submit" name="bought_product" value="{{ product.id }}">Buy</button>
				</form>
				{% else %}
					<p>"This Item is Unavailable. Come back next time!"</p>
				{% endif %}
			{% else %}
				<a href="{% url 'merchstore:product_update' product.id %}" class="button">Update Your Product Here!</a>
			{% endif %}
		</section>
	</main>
{% endblock %}

merchstore/templates/merchstore/product_list.html
{% extends 'merchstore/base.html' %}
{% block content %}
<main class="full-flex">
	{% if user.is_authenticated %}
	<section class="card full-flex">
		<h1>Your Products</h1>
		{% if user.profile.products.all|length == 0 %}
		<h2>Nothing for now. Click below to...</h2>
		<br>
		{% endif %}
		<a href="{% url 'merchstore:product_create' %}" class="button">+ Add a new product</a>
		<section class="product-grid">
			{% for product in user.profile.products.all %}
			<section class="product-item">
				<section>
					<a href="{% url 'merchstore:product_detail' product.id %}"><p class="bold">{{product.product_type}}: {{ product.name }}</p></a>
					<p>PHP {{ product.price|floatformat:2 }}</p>
				</section>
				<section>
					<p>{{ product.stock }} in stock</p>
					<p class="status-chip">{{ product.status }}</p>
				</section>
			</section>
			{% endfor %}
		</section>
	</section>
	{% endif %}
	{% if products.all|length != user.profile.products.all|length %}
	<section class="card full-flex">
		<h1>All Products</h1>
		<section class="product-grid">
			{% for product in products.all %}
			{% if product.owner != user.profile %}
			<section class="product-item">
				<section>
					<a href="{% url 'merchstore:product_detail' product.id %}"><p class="bold">{{product.product_type}}: {{ product.name }}</p></a>
					<p>PHP {{ product.price|floatformat:2 }}</p>
				</section>
				<section>
					<p>{{ product.stock }} in stock</p>
					<p class="status-chip">{{ product.status }}</p>
				</section>
			</section>
			{% endif %}
			{% endfor %}
		</section>
	</section>
	{% endif %}
	{% if products.all|length == 0 and not user.is_authenticated %}
	<p>Sorry, nothing's for sale. How about you login and make your own products?</p>
	{% endif %}
</main>
{% endblock %}

merchstore/templates/merchstore/product_update.html
{% extends 'merchstore/base.html' %}
{% block title %}Updating {{product.name}}...{% endblock %}
{% block content %}
<main>
	<section class="card full-flex">
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<button type="submit" name="form_type" value="product">Update</button>
	</form>
	</section>
</main>
{% endblock %}

merchstore/templates/merchstore/transaction_list.html
{% extends 'merchstore/base.html' %}
{% block content %}
<main class="card">
	<h1>Your Orders</h1>
	{% regroup transactions by buyer as buyer_list %}
	{% for buyer in buyer_list %}
		<section class="transaction-list">
			<h2>{{buyer.grouper}}</h2>
			<ul>
				{% for transaction_entry in buyer.list %}
					<li class="product-item">
						<section>
							<p class="bold">{{ transaction_entry  }}</p>
							<p>PHP {{ transaction_entry.product.price|floatformat:2 }} per item</p>
						</section>
						<section>
							<p class="status-chip">{{ transaction_entry.status }}</p>
						</section>
					</li>
				{% endfor %}
			</ul>
		</section>
	{% endfor %}
</main>
{% endblock %}